const icon=(name)=>{const paths={phone:'<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.8 19.8 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6A19.8 19.8 0 0 1 2.12 4.18 2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.69 2.8a2 2 0 0 1-.45 2.11L8.08 9.9a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.33 1.84.56 2.8.69A2 2 0 0 1 22 16.92z"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8z"/>',cart:'<circle cx="9" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M3 4h2l2.5 11h11l2-7H7"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0z"/><circle cx="12" cy="10" r="2.5"/>',facebook:'<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3.5l.5-4h-4V7a1 1 0 0 1 1-1h3z"/>',linkedin:'<rect x="3" y="9" width="4" height="12"/><circle cx="5" cy="5" r="2"/><path d="M11 21V9h4v2c1-2 6-3 6 3v7h-4v-6c0-2-2-3-2 0v6z"/>',youtube:'<path d="M22 12s0-4-1-6c-.5-1-1.5-1.5-3-1.7C16 4 12 4 12 4s-4 0-6 .3C4.5 4.5 3.5 5 3 6c-1 2-1 6-1 6s0 4 1 6c.5 1 1.5 1.5 3 1.7 2 .3 6 .3 6 .3s4 0 6-.3c1.5-.2 2.5-.7 3-1.7 1-2 1-6 1-6z"/><path d="m10 9 5 3-5 3z"/>',whatsapp:'<path d="M21 11.5a8.5 8.5 0 0 1-12.6 7.4L3 20.5l1.6-5.2A8.5 8.5 0 1 1 21 11.5z"/><path d="M8.2 7.7c.3-.6.6-.6.9-.6h.4c.2 0 .4.1.5.5l.8 1.9c.1.3 0 .5-.1.7l-.6.7c-.2.2-.2.4 0 .7.7 1.2 1.7 2.1 3 2.7.3.2.5.1.7-.1l.8-1c.2-.2.4-.3.7-.2l1.9.9c.3.2.4.3.4.5 0 .5-.3 1.5-1 2-.7.6-1.7.9-2.8.6-1.2-.3-3.7-1.2-5.8-3.8-1.7-2.1-2-3.8-1.8-4.7.2-.5.5-.9 1-1.3z"/>',x:'<path d="M18 6 6 18M6 6l12 12"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>'};return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||''}</svg>`};

const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
const active=(file)=>page===file?' class="active"':'';
const topbar=document.querySelector('.topbar');
if(topbar)topbar.innerHTML=`<div class="shell topbar-inner"><div class="top-social"><a href="https://www.facebook.com/chanderiyaMS" target="_blank" rel="noopener" aria-label="Facebook">${icon('facebook')}</a><a href="https://in.linkedin.com/company/chanderiya-marketing-and-sales" target="_blank" rel="noopener" aria-label="LinkedIn">${icon('linkedin')}</a><a href="https://www.youtube.com/@cmschanderiya" target="_blank" rel="noopener" aria-label="YouTube">${icon('youtube')}</a></div><span class="top-message">Serving institutions with trust since 2011</span><div class="top-links"><a href="tel:+919027398484">${icon('phone')}<span>+91 90273 98484</span></a><a href="tel:+919319038666">${icon('phone')}<span>+91 93190 38666</span></a><a href="mailto:chanderiya.group@gmail.com">${icon('mail')}<span>chanderiya.group@gmail.com</span></a></div></div>`;

const header=document.querySelector('.site-header');
if(header)header.innerHTML=`<div class="shell nav-wrap"><a class="brand" href="index.html" aria-label="Chanderiya home"><img src="assets/chanderiya-logo.jpeg" alt="Chanderiya Marketing and Sales"><span>Chanderiya<small>Marketing & Sales</small></span></a><button class="menu-toggle" type="button" aria-label="Open navigation" aria-expanded="false">${icon('menu')}</button><nav class="main-nav" aria-label="Primary navigation"><a${active('index.html')} href="index.html">Home</a><a${active('about-us.html')} href="about-us.html">About</a><a${active('shop.html')} href="shop.html">Products</a><a${active('services.html')} href="services.html">Services</a><a${active('contact.html')} href="contact.html">Contact</a></nav><div class="header-actions"><a class="header-icon" href="contact.html" aria-label="Profile and contact">${icon('user')}</a><a class="header-icon" href="shop.html" aria-label="Wishlist">${icon('heart')}</a>${page==='shop.html'?`<button class="header-icon cart-icon" type="button" data-cart-open aria-label="Open inquiry cart">${icon('cart')}<span data-cart-count>0</span></button>`:`<a class="header-icon cart-icon" href="shop.html" aria-label="Open inquiry cart">${icon('cart')}<span data-cart-count>0</span></a>`}<button class="button button-small nav-cta" type="button" data-enquiry-open>Request a quote</button></div></div>`;

const footer=document.querySelector('.site-footer');
if(footer)footer.innerHTML=`<div class="shell footer-grid"><div class="footer-brand"><a class="brand brand-footer" href="index.html"><img src="assets/chanderiya-logo.jpeg" alt=""><span>Chanderiya<small>Marketing & Sales</small></span></a><p>Reliable institutional products and services from Haridwar, Uttarakhand.</p><div class="footer-social"><a href="https://www.facebook.com/chanderiyaMS" target="_blank" rel="noopener" aria-label="Facebook">${icon('facebook')}</a><a href="https://in.linkedin.com/company/chanderiya-marketing-and-sales" target="_blank" rel="noopener" aria-label="LinkedIn">${icon('linkedin')}</a><a href="https://www.youtube.com/@cmschanderiya" target="_blank" rel="noopener" aria-label="YouTube">${icon('youtube')}</a><a href="https://wa.me/919027398484" target="_blank" rel="noopener" aria-label="WhatsApp">${icon('whatsapp')}</a></div></div><div><h4>Navigate</h4><a href="about-us.html">About us</a><a href="shop.html">Products</a><a href="services.html">Services</a><a href="contact.html">Contact</a></div><div><h4>Solutions</h4><a href="shop.html#furniture">Furniture</a><a href="shop.html#fire">Fire safety</a><a href="shop.html#water">Water purification</a><a href="shop.html#institutional">Institutional</a></div><div class="footer-contact"><h4>Contact</h4><a href="tel:+919027398484">${icon('phone')}<span>+91 90273 98484</span></a><a href="mailto:chanderiya.group@gmail.com">${icon('mail')}<span>chanderiya.group@gmail.com</span></a><p>${icon('pin')}<span>170, First Floor, Brahampuri, Haridwar, Uttarakhand 249401</span></p></div></div><div class="shell footer-bottom"><span>© <span data-year></span> Chanderiya Marketing & Sales.</span><div class="legal-links"><a href="privacy.html">Privacy Policy</a><a href="terms.html">Terms & Conditions</a><a href="shipping.html">Shipping Policy</a><a href="refund.html">Cancellation & Refund</a></div></div>`;

document.querySelectorAll('.whatsapp-fab').forEach(el=>{el.innerHTML=icon('whatsapp');el.setAttribute('aria-label','Chat with us on WhatsApp')});

document.body.insertAdjacentHTML('beforeend',`<div class="enquiry-modal" data-enquiry-modal aria-hidden="true"><div class="enquiry-backdrop" data-enquiry-close></div><div class="enquiry-dialog" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><button class="modal-close" type="button" data-enquiry-close aria-label="Close enquiry form">${icon('x')}</button><p class="eyebrow">Quick enquiry</p><h2 id="enquiry-title">Tell us what you need.</h2><p>Share a few details and continue securely on WhatsApp.</p><form data-popup-form><div class="form-row"><label>Your name<input name="name" required autocomplete="name" placeholder="Full name"></label><label>Phone number<input name="phone" required inputmode="tel" autocomplete="tel" placeholder="Mobile number"></label></div><label>Organization<input name="organization" autocomplete="organization" placeholder="Company or institution"></label><label>Requirement<select name="interest"><option>Furniture & workspaces</option><option>Hospital or institutional furniture</option><option>Fire safety equipment</option><option>Industrial water purification</option><option>Repair & maintenance service</option><option>Other requirement</option></select></label><label>Message<textarea name="message" required rows="4" placeholder="Quantity, specifications, location or service issue"></textarea></label><button class="button" type="submit">Continue on WhatsApp ${icon('whatsapp')}</button></form></div></div>`);

document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');if(toggle&&nav){toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
const modal=document.querySelector('[data-enquiry-modal]');const openModal=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll');setTimeout(()=>modal.querySelector('input')?.focus(),100)};const closeModal=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')};document.querySelectorAll('[data-enquiry-open]').forEach(el=>el.addEventListener('click',openModal));document.querySelectorAll('[data-enquiry-close]').forEach(el=>el.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))closeModal()});
const sendWhatsApp=(form)=>{const data=new FormData(form);const message=`Hello Chanderiya Marketing & Sales,\n\nName: ${data.get('name')}\nOrganization: ${data.get('organization')||'Not specified'}\nPhone: ${data.get('phone')}\n${data.get('location')?`Location: ${data.get('location')}\n`:''}Interested in: ${data.get('interest')}\n\nRequirement:\n${data.get('message')}`;window.open(`https://wa.me/919027398484?text=${encodeURIComponent(message)}`,'_blank','noopener')};document.querySelector('[data-popup-form]')?.addEventListener('submit',e=>{e.preventDefault();sendWhatsApp(e.currentTarget)});document.querySelector('[data-quote-form]')?.addEventListener('submit',e=>{e.preventDefault();sendWhatsApp(e.currentTarget)});
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});reveals.forEach(el=>observer.observe(el))}else reveals.forEach(el=>el.classList.add('visible'));
const catalogue=[
{name:'Premium Executive Desk',category:'Furniture',price:18999,offer:14999,save:21,image:'assets/Premium Executive Desk.jpg',position:'50% 50%',tag:'Workspace'},
{name:'Ergonomic Mesh Chair',category:'Furniture',price:9999,offer:7499,save:25,image:'assets/Ergonomic Mesh Chair.jpg',position:'50% 50%',tag:'Seating'},
{name:'Modular Office Workstation',category:'Furniture',price:24999,offer:19999,save:20,image:'assets/modular-office-workstation.jpg',position:'50% 50%',tag:'Modular'},
{name:'Conference Room Table',category:'Furniture',price:32999,offer:26999,save:18,image:'assets/Conference Room Table.jpg',position:'50% 50%',tag:'Boardroom'},
{name:'ABC Fire Extinguisher',category:'Fire Safety',price:2499,offer:1999,save:20,image:'assets/ABC Fire Extinguisher.jpg',position:'50% 50%',tag:'Certified'},
{name:'Fire Hose Reel System',category:'Fire Safety',price:8999,offer:7299,save:19,image:'assets/Fire Hose Reel System.jpg',position:'50% 50%',tag:'Safety'},
{name:'Industrial Protective Suit',category:'Fire Safety',price:6999,offer:5499,save:21,image:'assets/certified fire-fighting.png',position:'50% 50%',tag:'PPE'},
{name:'Industrial RO Plant',category:'Water Systems',price:89999,offer:74999,save:17,image:'assets/Commercial RO System.jpg',position:'50% 50%',tag:'Industrial'},
{name:'Commercial RO System',category:'Water Systems',price:44999,offer:37999,save:16,image:'assets/Commercial RO System.jpg',position:'50% 50%',tag:'Purification'},
{name:'Semi-Fowler Hospital Bed',category:'Institutional',price:22999,offer:18999,save:17,image:'assets/reliable-supply-img.png',position:'50% 50%',tag:'Healthcare'},
{name:'Steel Storage Almirah',category:'Institutional',price:16999,offer:13999,save:18,image:'assets/Premium Executive Desk.jpg',position:'50% 50%',tag:'Storage'},
{name:'Dual-Seater School Desk',category:'Institutional',price:7999,offer:6499,save:19,image:'assets/modular-office-workstation.jpg',position:'50% 50%',tag:'Education'}
];
const money=value=>`₹${value.toLocaleString('en-IN')}`;
let wishlist=[];try{wishlist=JSON.parse(localStorage.getItem('chanderiya-wishlist')||'[]')}catch(e){wishlist=[]}
const productMarkup=product=>`<article class="commerce-card"><div class="commerce-image"><img src="${product.image}" style="object-position:${product.position}" alt="${product.name}" loading="lazy"><span class="save-badge">Save ${product.save}%</span><div class="card-actions"><button type="button" data-wishlist="${product.name}" class="${wishlist.includes(product.name)?'wishlisted':''}" aria-label="Add ${product.name} to wishlist">${icon('heart')}</button><button type="button" data-view-product="${product.name}" aria-label="Quick view ${product.name}">${icon('user')}</button></div></div><div class="commerce-body"><span class="product-category">${product.category} · ${product.tag}</span><h3>${product.name}</h3><div class="rating" aria-label="Rated 4.8 out of 5"><span>★★★★★</span><small>4.8</small></div><div class="price-row"><strong>${money(product.offer)}</strong><del>${money(product.price)}</del></div><small class="starting-label">Starting price</small><button class="add-cart-button" type="button" data-add-item="${product.name}">${icon('cart')} Add to inquiry cart</button></div></article>`;
const featured=document.querySelector('#featured-products');if(featured)featured.innerHTML=catalogue.slice(0,4).map(productMarkup).join('');
const productSection=document.querySelector('.product-section .shell');let shopState={page:1,perPage:6,category:'All',price:'all',search:'',sort:'featured'};
if(productSection){productSection.innerHTML=`<div class="shop-toolbar"><button class="mobile-filter-button" type="button" data-filter-toggle>Filters</button><div><span data-result-count></span><select data-sort aria-label="Sort products"><option value="featured">Sort: Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option><option value="saving">Biggest saving</option></select></div></div><div class="catalogue-layout"><aside class="filter-sidebar" data-filter-sidebar><div class="filter-title"><h2>Filter products</h2><button type="button" data-filter-close>×</button></div><label class="product-search">Search<input type="search" data-product-search placeholder="Search catalogue"></label><div class="filter-group"><h3>Category</h3>${['All','Furniture','Institutional','Fire Safety','Water Systems'].map((c,i)=>`<label><input type="radio" name="category" value="${c}" ${i===0?'checked':''}><span>${c}</span><b>${c==='All'?catalogue.length:catalogue.filter(p=>p.category===c).length}</b></label>`).join('')}</div><div class="filter-group"><h3>Starting price</h3><label><input type="radio" name="price" value="all" checked><span>All prices</span></label><label><input type="radio" name="price" value="under10000"><span>Under ₹10,000</span></label><label><input type="radio" name="price" value="10000to25000"><span>₹10,000 – ₹25,000</span></label><label><input type="radio" name="price" value="above25000"><span>Above ₹25,000</span></label></div><button class="clear-filters" type="button" data-clear-filters>Clear all filters</button></aside><div class="catalogue-results"><div class="commerce-grid" data-catalogue-grid></div><nav class="pagination" data-pagination aria-label="Product pages"></nav><p class="price-note">Displayed prices are indicative starting prices. Final quotation depends on specification, quantity, tax and delivery.</p></div></div><div class="filter-overlay" data-filter-close></div>`;
productSection.querySelector('.catalogue-results').insertAdjacentHTML('afterbegin','<div class="catalogue-heading"><p class="eyebrow">Product catalogue</p><h1>All Products</h1><p>Browse our institutional products and add the items you need to your enquiry cart.</p></div>');
const grid=productSection.querySelector('[data-catalogue-grid]');const pagination=productSection.querySelector('[data-pagination]');const resultCount=productSection.querySelector('[data-result-count]');
const filteredProducts=()=>{let items=catalogue.filter(p=>shopState.category==='All'||p.category===shopState.category).filter(p=>p.name.toLowerCase().includes(shopState.search.toLowerCase())).filter(p=>shopState.price==='all'||(shopState.price==='under10000'&&p.offer<10000)||(shopState.price==='10000to25000'&&p.offer>=10000&&p.offer<=25000)||(shopState.price==='above25000'&&p.offer>25000));if(shopState.sort==='low')items.sort((a,b)=>a.offer-b.offer);if(shopState.sort==='high')items.sort((a,b)=>b.offer-a.offer);if(shopState.sort==='saving')items.sort((a,b)=>b.save-a.save);return items};
const renderShop=()=>{const items=filteredProducts();const pages=Math.max(1,Math.ceil(items.length/shopState.perPage));shopState.page=Math.min(shopState.page,pages);const start=(shopState.page-1)*shopState.perPage;grid.innerHTML=items.slice(start,start+shopState.perPage).map(productMarkup).join('')||'<div class="no-products"><h3>No matching products</h3><p>Try clearing a filter or searching another term.</p></div>';resultCount.textContent=`Showing ${items.length?start+1:0}–${Math.min(start+shopState.perPage,items.length)} of ${items.length} products`;pagination.innerHTML=Array.from({length:pages},(_,i)=>`<button type="button" class="${shopState.page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');bindCardActions();pagination.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{shopState.page=Number(b.dataset.page);renderShop();productSection.scrollIntoView({behavior:'smooth'})}))};
productSection.querySelectorAll('input[name="category"]').forEach(input=>input.addEventListener('change',()=>{shopState.category=input.value;shopState.page=1;renderShop()}));productSection.querySelectorAll('input[name="price"]').forEach(input=>input.addEventListener('change',()=>{shopState.price=input.value;shopState.page=1;renderShop()}));productSection.querySelector('[data-product-search]').addEventListener('input',e=>{shopState.search=e.target.value;shopState.page=1;renderShop()});productSection.querySelector('[data-sort]').addEventListener('change',e=>{shopState.sort=e.target.value;renderShop()});productSection.querySelector('[data-clear-filters]').addEventListener('click',()=>{shopState={...shopState,page:1,category:'All',price:'all',search:''};productSection.querySelector('input[name="category"][value="All"]').checked=true;productSection.querySelector('input[name="price"][value="all"]').checked=true;productSection.querySelector('[data-product-search]').value='';renderShop()});const sidebar=productSection.querySelector('[data-filter-sidebar]');productSection.querySelector('[data-filter-toggle]').addEventListener('click',()=>sidebar.classList.add('open'));productSection.querySelectorAll('[data-filter-close]').forEach(el=>el.addEventListener('click',()=>sidebar.classList.remove('open')));renderShop()}
function bindCardActions(){document.querySelectorAll('[data-wishlist]').forEach(button=>{button.onclick=()=>{const name=button.dataset.wishlist;wishlist=wishlist.includes(name)?wishlist.filter(item=>item!==name):[...wishlist,name];localStorage.setItem('chanderiya-wishlist',JSON.stringify(wishlist));button.classList.toggle('wishlisted')}});document.querySelectorAll('[data-view-product]').forEach(button=>{button.onclick=()=>{openModal();const field=modal.querySelector('textarea[name="message"]');if(field)field.value=`I would like details and a quotation for ${button.dataset.viewProduct}.`}})}
bindCardActions();
document.addEventListener('click',event=>{const button=event.target.closest('[data-add-item]');if(!button)return;const item=button.dataset.addItem;if(!cart.includes(item)){cart.push(item);saveCart()}button.innerHTML=`${icon('cart')} Added ✓`;button.classList.add('added');setTimeout(()=>{button.innerHTML=`${icon('cart')} Add to inquiry cart`;button.classList.remove('added')},1500)});
const storageKey='chanderiya-inquiry';let cart=[];try{cart=JSON.parse(localStorage.getItem(storageKey)||'[]')}catch(e){cart=[]}const drawer=document.querySelector('.cart-drawer');const cartItems=document.querySelector('[data-cart-items]');const cartEmpty=document.querySelector('[data-cart-empty]');const cartLink=document.querySelector('[data-cart-whatsapp]');function saveCart(){localStorage.setItem(storageKey,JSON.stringify(cart));renderCart()}function renderCart(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cart.length);if(!cartItems)return;cartItems.innerHTML=cart.map((item,index)=>`<div class="cart-item"><span>${item}</span><button type="button" data-remove="${index}" aria-label="Remove ${item}">×</button></div>`).join('');cartEmpty.hidden=cart.length>0;cartLink.href=`https://wa.me/919027398484?text=${encodeURIComponent('Hello Chanderiya Marketing & Sales, I would like a quotation for:\n\n'+cart.map((item,i)=>`${i+1}. ${item}`).join('\n')+'\n\nPlease contact me with details.')}`;cartItems.querySelectorAll('[data-remove]').forEach(button=>button.addEventListener('click',()=>{cart.splice(Number(button.dataset.remove),1);saveCart()}))}document.querySelectorAll('[data-add-item]').forEach(button=>button.addEventListener('click',()=>{const item=button.dataset.addItem;if(!cart.includes(item)){cart.push(item);saveCart()}button.textContent='Added ✓';button.classList.add('added');setTimeout(()=>{button.textContent='Add to inquiry';button.classList.remove('added')},1500)}));document.querySelectorAll('[data-cart-open]').forEach(button=>button.addEventListener('click',()=>{drawer?.classList.add('open');drawer?.setAttribute('aria-hidden','false');document.body.classList.add('no-scroll')}));document.querySelectorAll('[data-cart-close]').forEach(button=>button.addEventListener('click',()=>{drawer?.classList.remove('open');drawer?.setAttribute('aria-hidden','true');document.body.classList.remove('no-scroll')}));document.querySelector('[data-cart-clear]')?.addEventListener('click',()=>{cart=[];saveCart()});renderCart();
